version: "2"
services:
  twc-controller:
    image: shreddedbacon/twc-controller:arm32v6-rpi-v0.0.2
    privileged: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./config.yml:/config.yml
      - /dev:/dev
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
  shellinabox:
    image: shreddedbacon/rpi-shellinabox
    restart: always
    ports:
      - 2222:4200
    environment:
      - SIAB_SSL=false
      - SIAB_ADDUSER=false
      - SIAB_SERVICE=/:SSH:172.17.0.1
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m

volumes:
  portainer_data:
