version: "2"
services:
  twc-controller:
    image: shreddedbacon/twc-controller:arm32v6-rpi-v0.0.3
    privileged: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./config.yml:/config.yml
      - /dev:/dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    environment:
      POWERWALL_HOST: http://fake-powerwall:8080
  fake-powerwall:
    image: shreddedbacon/fake-powerwall:arm32v6-rpi-v0.0.4
    env_file: .env.fakepowerwall
  shellinabox:
    image: fhuegli/rpi-shellinabox
    restart: always
    ports:
      - 4200:4200
    environment:
      - SIAB_SSL=false
      - SIAB_ADDUSER=false
      - SIAB_SERVICE=/:SSH:172.17.0.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
