wiringMaxAmpsAllTWC: 32
wiringMaxAmpsPerTWC: 32
minAmpsPerTWC: 6
supplyVoltage: 240
supplyPhases: 1
debugLevel: 0
serial:
  port: /dev/ttyUSB0
  baudRate: 9600
availableAmps: 6
powerwall: http://192.168.1.50
enablePowerwall: true
autoStartStopInterval: false
powerOffset: 0
powerwallCheckInterval: 1
